"""Yapı FastAPI application entrypoint (Section 2.5, 8.1, 13.2)."""
import logging
from contextlib import asynccontextmanager

# Verify TLS against the OS trust store (Windows/macOS/Linux system CAs) rather
# than only the bundled certifi roots. This is required when a corporate proxy
# or local antivirus (e.g. Norton "Web/Mail Shield") performs HTTPS scanning and
# re-signs outbound connections with a local root CA — that root is in the OS
# store but not in certifi, so otherwise every outbound API call (Anthropic,
# Resend, …) fails with CERTIFICATE_VERIFY_FAILED. Must run before any HTTPS
# client is created. No-op on platforms whose system store already matches certifi.
try:
    import truststore

    truststore.inject_into_ssl()
except Exception:  # pragma: no cover - optional dependency / platform quirks
    logging.getLogger("yapi").warning("truststore unavailable; falling back to certifi CA bundle")

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.httpsredirect import HTTPSRedirectMiddleware

from app.config import settings
from app.middleware.errors import CatchAllErrorMiddleware, register_error_handlers
from app.middleware.rate_limit import RateLimitMiddleware
from app.middleware.security_headers import SecurityHeadersMiddleware
from app.startup import run_migrations

# Routers
from app.api import (
    ai,
    ai_conversations,
    ai_import,
    document_capture,
    approvals,
    audit,
    budget_templates,
    auth,
    cashflow,
    costs,
    custom_categories,
    equipment,
    imports,
    invoices,
    notifications,
    projects,
    reminders,
    reports,
    settings as settings_router,
    subcontractors,
    uploads,
    users,
    variations,
)

logging.basicConfig(level=logging.INFO)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Reconcile the database schema to the models on every boot, regardless of
    # how the platform builds/starts the container (see app/startup.py).
    run_migrations()
    yield


app = FastAPI(
    title="Yapı API",
    description="İnşaat Proje Yönetim Yazılımı — REST API",
    version="1.0.0",
    docs_url="/docs",
    openapi_url="/openapi.json",
    lifespan=lifespan,
)

# --- Security middleware (Section 8.1) ---
# Added first => innermost user middleware. It catches unhandled exceptions and
# turns them into the 500 envelope so the response still flows back out through
# CORSMiddleware (below) and carries Access-Control-Allow-Origin. Without this,
# a 500 is generated by Starlette outside the CORS layer and looks like a CORS
# error to the browser.
app.add_middleware(CatchAllErrorMiddleware)

if settings.is_production:
    app.add_middleware(HTTPSRedirectMiddleware)  # redirect HTTP -> HTTPS

app.add_middleware(SecurityHeadersMiddleware)  # CR-002-I: security headers
app.add_middleware(RateLimitMiddleware)

# CORS: only allow the Vercel frontend origin(s) (Section 8.1).
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

register_error_handlers(app)

# --- Health check (Section 13.2) ---
@app.get("/health", tags=["health"])
def health():
    return {"status": "ok"}


# --- API v1 routers ---
API_PREFIX = "/api/v1"
for r in (
    auth.router,
    projects.router,
    costs.router,
    invoices.router,
    subcontractors.router,
    equipment.router,
    cashflow.router,
    imports.router,
    reminders.router,
    reports.router,
    ai.router,
    ai_conversations.router,
    uploads.router,
    audit.router,
    settings_router.router,
    custom_categories.router,
    ai_import.router,
    document_capture.router,
    variations.router,
    approvals.router,
    budget_templates.router,
    users.router,
    notifications.router,
):
    app.include_router(r, prefix=API_PREFIX)
