"""Yapı FastAPI application entrypoint (Section 2.5, 8.1, 13.2)."""
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.httpsredirect import HTTPSRedirectMiddleware

from app.config import settings
from app.middleware.errors import CatchAllErrorMiddleware, register_error_handlers
from app.middleware.rate_limit import RateLimitMiddleware
from app.middleware.security_headers import SecurityHeadersMiddleware
from app.startup import run_migrations

# Routers
from app.api import (
    ai,
    ai_import,
    approvals,
    audit,
    budget_templates,
    auth,
    cashflow,
    costs,
    custom_categories,
    equipment,
    imports,
    invoices,
    notifications,
    projects,
    reminders,
    reports,
    settings as settings_router,
    subcontractors,
    uploads,
    users,
    variations,
)

logging.basicConfig(level=logging.INFO)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Reconcile the database schema to the models on every boot, regardless of
    # how the platform builds/starts the container (see app/startup.py).
    run_migrations()
    yield


app = FastAPI(
    title="Yapı API",
    description="İnşaat Proje Yönetim Yazılımı — REST API",
    version="1.0.0",
    docs_url="/docs",
    openapi_url="/openapi.json",
    lifespan=lifespan,
)

# --- Security middleware (Section 8.1) ---
# Added first => innermost user middleware. It catches unhandled exceptions and
# turns them into the 500 envelope so the response still flows back out through
# CORSMiddleware (below) and carries Access-Control-Allow-Origin. Without this,
# a 500 is generated by Starlette outside the CORS layer and looks like a CORS
# error to the browser.
app.add_middleware(CatchAllErrorMiddleware)

if settings.is_production:
    app.add_middleware(HTTPSRedirectMiddleware)  # redirect HTTP -> HTTPS

app.add_middleware(SecurityHeadersMiddleware)  # CR-002-I: security headers
app.add_middleware(RateLimitMiddleware)

# CORS: only allow the Vercel frontend origin(s) (Section 8.1).
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

register_error_handlers(app)

# --- Health check (Section 13.2) ---
@app.get("/health", tags=["health"])
def health():
    return {"status": "ok"}


# --- API v1 routers ---
API_PREFIX = "/api/v1"
for r in (
    auth.router,
    projects.router,
    costs.router,
    invoices.router,
    subcontractors.router,
    equipment.router,
    cashflow.router,
    imports.router,
    reminders.router,
    reports.router,
    ai.router,
    uploads.router,
    audit.router,
    settings_router.router,
    custom_categories.router,
    ai_import.router,
    variations.router,
    approvals.router,
    budget_templates.router,
    users.router,
    notifications.router,
):
    app.include_router(r, prefix=API_PREFIX)
